<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 01/02/2018
 * Time: 14:12
 */

class Controller_Admin_Index
    extends Controller_Admin

{
    const TITLE = 'Dashboard';

    public function run()
    {
        $id = $this->getUser();
        if(!$id){
            $this->_redirectAdmin('user/login');
        }
        $this->renderLayout();

    }

    public function beforeRenderLayout()
    {
        parent::beforeRenderLayout(); // TODO: Change the autogenerated stub
        $this->_title = self::TITLE;
        $this->_type = 'dashboard';
        $breadCrumbs = array(
            array(
                'label' => 'Home',
                'url' => Bootstrap::getUrlAdmin(),
            ),
            array(
                'label' => 'Dashboard',
            )
        );
        $this->setBreadCrumbs($breadCrumbs);
    }
    public function renderLayout()
    {
        parent::renderLayout(); // TODO: Change the autogenerated stub
        $this->beforeRenderLayout();
        $this->_render('admin/index');

    }
}