<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 14/03/2018
 * Time: 09:15
 */
class Controller_Admin_User_Info extends Controller_Admin{

    const TITLE = "Profile";
    public function __construct()
    {
        $this->_title = self::TITLE;
    }
    public function run()
    {
        $this->renderLayout();
    }
    public function beforeRenderLayout()
    {
        parent::beforeRenderLayout(); // TODO: Change the autogenerated stub
        $breadCrumbs = array(
            array(
                'label' => 'Home',
                'url' => Bootstrap::getUrlAdmin(),
            ),
            array(
                'label' => $this->getTitle(),
            )
        );
        $this->setBreadCrumbs($breadCrumbs);

    }

    public function renderLayout()
    {
        parent::renderLayout();
        $this->_render('admin/user/info');
    }
}