<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 07/03/2018
 * Time: 17:40
 */
class Controller_Admin_User_Login
    extends Controller_Admin
{
    const TITLE = 'webshop login';

    public function __construct()
    {

    }

    public function run()
    {
        $action = $this->getParam('action','');
        if($action != 'logout'){
            $this->beforeAction();
        }
        if($action && method_exists($this,$action)){
            $this->$action();
        }
        else{
            $this->renderLayout();
        }
    }
    public function beforeAction(){
        if($this->getUser()){
            $this->_redirectAdmin();
        }
    }
    public function beforeRenderLayout()
    {
        parent::beforeRenderLayout(); // TODO: Change the autogenerated stub
        $this->setTitle(self::TITLE);
        $error = $this->getErrorSession();
        if($error){
            $this->setError($error);
            $this->unsetErrorSession();
        }
    }
    public function renderLayout()
    {
        parent::renderLayout(); // TODO: Change the autogenerated stub
        $this->beforeRenderLayout();
        $this->_render('admin/user/index');
    }

    public function forgotPassword(){

    }
    public function login(){
        $username = $this->getParam('username');
        $password = $this->getParam('password');
        if(!$username || !$password){
            $this->_redirectAdmin('user/login','Thiếu dữ liệu');
        }
        $model_account = Bootstrap::getModel('account');
        $model_account->setUsername($username);
        $model_account->setPassword($password);
        try{
            $login = $model_account->login();
            Session::setKey(self::KEY_ADMIN_TOKEN,$login['token']);
            $this->_redirectAdmin();

        }catch (Exception $e){
            $this->_redirectAdmin('user/login',$e->getMessage());
        }
    }
    public function logout(){
        $model_account = $this->getUser();
        if(!$model_account){
            $this->_redirectAdmin('user/login');
        }
        try{
            $model_account->logout();
            Session::unsetKey(self::KEY_ADMIN_TOKEN);
            $this->_redirectAdmin('user/login');
        }catch (Exception $e){
            echo $e->getMessage();
        }
    }
}